name: Main CI-pipeline

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Checkstyle (lab1)
        working-directory: lab1
        run: make check_fmt

      - name: Run test (lab1)
        working-directory: lab1
        run: make test

      - name: Checkstyle (lab2)
        working-directory: lab2
        run: make check_fmt
        
      - name: Run test (lab2)
        working-directory: lab2
        run: make test
